<?php return array(
  array (
    'key' => 'field__logo_footer__luca_logo',
    'label' => 'Footer Logo',
    'name' => 'logo_footer',
    'type' => 'image',
    'instructions' => 'Choose this to override footer logo.',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array (
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'return_format' => 'array',
    'preview_size' => 'acf_thumbnail',
    'library' => 'all',
    'min_width' => '',
    'min_height' => '',
    'min_size' => '',
    'max_width' => '',
    'max_height' => '',
    'max_size' => '',
    'mime_types' => '',
  ),
);