<?php if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
    'key' => 'group_5808b274c7d49',
    'title' => 'Services Content Block 1',
    'fields' => array (
        array (
            'key' => 'field_5808b27f33dd7',
            'label' => 'Content',
            'name' => 'content_1',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
        ),
        array (
          'key' => 'field_5808b27f33dd8',
          'label' => 'Background',
          'name' => 'background_type_1',
          'type' => 'radio',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array (
            'none' => 'None',
            'color' => 'Solid color',
            'image' => 'Image',
          ),
          'other_choice' => 0,
          'save_other_choice' => 0,
          'default_value' => 'none',
          'layout' => 'vertical',
        ),
        array (
          'key' => 'field_5808b27f33dd9',
          'label' => 'Background image',
          'name' => 'image_1',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_5808b27f33dd8',
                        'operator' => '==',
                        'value' => 'image',
                    ),
                ),
            ),
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'acf_thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array (
            'key' => 'field_5808b27f33de0',
            'label' => 'Background Color',
            'name' => 'color_1',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_5808b27f33dd8',
                        'operator' => '==',
                        'value' => 'color',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'template-services.php',
            ),
        ),
    ),
    'menu_order' => 1,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array (
        0 => 'the_content',
    ),
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array (
    'key' => 'group_5809b274c7d49',
    'title' => 'Services Content Block 2',
    'fields' => array (
        array (
            'key' => 'field_5809b27f33dd7',
            'label' => 'Content',
            'name' => 'content_2',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
        ),
        array (
          'key' => 'field_5809b27f33dd8',
          'label' => 'Background',
          'name' => 'background_type_2',
          'type' => 'radio',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array (
            'none' => 'None',
            'color' => 'Solid color',
            'image' => 'Image',
          ),
          'other_choice' => 0,
          'save_other_choice' => 0,
          'default_value' => 'none',
          'layout' => 'vertical',
        ),
        array (
          'key' => 'field_5809b27f33dd9',
          'label' => 'Background image',
          'name' => 'image_2',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_5809b27f33dd8',
                        'operator' => '==',
                        'value' => 'image',
                    ),
                ),
            ),
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'acf_thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array (
            'key' => 'field_5809b27f33de0',
            'label' => 'Background Color',
            'name' => 'color_2',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_5809b27f33dd8',
                        'operator' => '==',
                        'value' => 'color',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'template-services.php',
            ),
        ),
    ),
    'menu_order' => 2,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array (
    'key' => 'group_50d0369b6c903',
    'title' => 'Columns Type 2',
    'fields' => array (
        array (
          'key' => 'field_50d0b27f33dd8',
          'label' => 'Background',
          'name' => 'background_type_cols',
          'type' => 'radio',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array (
            'none' => 'None',
            'color' => 'Solid color',
            'image' => 'Image',
          ),
          'other_choice' => 0,
          'save_other_choice' => 0,
          'default_value' => 'none',
          'layout' => 'vertical',
        ),
        array (
          'key' => 'field_50d0b27f33dd9',
          'label' => 'Background image',
          'name' => 'image_cols',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_50d0b27f33dd8',
                        'operator' => '==',
                        'value' => 'image',
                    ),
                ),
            ),
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'acf_thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array (
            'key' => 'field_50d0b27f33de0',
            'label' => 'Background Color',
            'name' => 'color_cols',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_50d0b27f33dd8',
                        'operator' => '==',
                        'value' => 'color',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),
        array (
            'key' => 'field_50d037e303106',
            'label' => 'Columns',
            'name' => 'columns_2_columns',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => '',
            'max' => '',
            'layout' => 'block',
            'button_label' => 'Add Column',
            'sub_fields' => array (
                array (
                    'key' => 'field_50d037e903107',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array (
                    'key' => 'field_50d037f303108',
                    'label' => 'Title',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array (
                    'key' => 'field_50d037f703109',
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                ),
                array (
                    'key' => 'field_50d037a303111',
                    'label' => 'Link title',
                    'name' => 'link_title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array (
                    'key' => 'field_50d037f303110',
                    'label' => 'Link url',
                    'name' => 'link_url',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
            ),
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'template-services.php',
            ),
        ),
    ),
    'menu_order' => 3,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => ['the_content'],
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array (
    'key' => 'group_5810b274c7d49',
    'title' => 'Services Content Block 3',
    'fields' => array (
        array (
            'key' => 'field_5810b27f33dd7',
            'label' => 'Content',
            'name' => 'content_3',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
        ),
        array (
          'key' => 'field_5810b27f33dd8',
          'label' => 'Background',
          'name' => 'background_type_3',
          'type' => 'radio',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array (
            'none' => 'None',
            'color' => 'Solid color',
            'image' => 'Image',
          ),
          'other_choice' => 0,
          'save_other_choice' => 0,
          'default_value' => 'none',
          'layout' => 'vertical',
        ),
        array (
          'key' => 'field_5810b27f33dd9',
          'label' => 'Background image',
          'name' => 'image_3',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_5810b27f33dd8',
                        'operator' => '==',
                        'value' => 'image',
                    ),
                ),
            ),
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'acf_thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array (
            'key' => 'field_5810b27f33de0',
            'label' => 'Background Color',
            'name' => 'color_3',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_5810b27f33dd8',
                        'operator' => '==',
                        'value' => 'color',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'template-services.php',
            ),
        ),
    ),
    'menu_order' => 4,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array (
    'key' => 'group_5811b274c7d49',
    'title' => 'Services Content Block 4',
    'fields' => array (
        array (
            'key' => 'field_5811b27f33dd7',
            'label' => 'Content',
            'name' => 'content_4',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
        ),
        array (
          'key' => 'field_5811b27f33dd8',
          'label' => 'Background',
          'name' => 'background_type_4',
          'type' => 'radio',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array (
            'none' => 'None',
            'color' => 'Solid color',
            'image' => 'Image',
          ),
          'other_choice' => 0,
          'save_other_choice' => 0,
          'default_value' => 'none',
          'layout' => 'vertical',
        ),
        array (
          'key' => 'field_5811b27f33dd9',
          'label' => 'Background image',
          'name' => 'image_4',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_5811b27f33dd8',
                        'operator' => '==',
                        'value' => 'image',
                    ),
                ),
            ),
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'acf_thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array (
            'key' => 'field_5811b27f33de0',
            'label' => 'Background Color',
            'name' => 'color_4',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_5811b27f33dd8',
                        'operator' => '==',
                        'value' => 'color',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'template-services.php',
            ),
        ),
    ),
    'menu_order' => 5,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => [0 => 'the_content'],
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array (
    'key' => 'group_5208b274c7d49',
    'title' => 'Services Content Block 5',
    'fields' => array (
        array (
            'key' => 'field_5208b27f33dd7',
            'label' => 'Content',
            'name' => 'content_5',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
        ),
        array (
          'key' => 'field_5208b27f33dd8',
          'label' => 'Background',
          'name' => 'background_type_5',
          'type' => 'radio',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array (
            'none' => 'None',
            'color' => 'Solid color',
            'image' => 'Image',
          ),
          'other_choice' => 0,
          'save_other_choice' => 0,
          'default_value' => 'none',
          'layout' => 'vertical',
        ),
        array (
          'key' => 'field_5208b27f33dd9',
          'label' => 'Background image',
          'name' => 'image_5',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_5208b27f33dd8',
                        'operator' => '==',
                        'value' => 'image',
                    ),
                ),
            ),
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'acf_thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array (
            'key' => 'field_5208b27f33de0',
            'label' => 'Background Color',
            'name' => 'color_5',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_5208b27f33dd8',
                        'operator' => '==',
                        'value' => 'color',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'template-services.php',
            ),
        ),
    ),
    'menu_order' => 6,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array (
        0 => 'the_content',
    ),
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array (
    'key' => 'group_5209b274c7d49',
    'title' => 'Services Content Block 6',
    'fields' => array (
        array (
            'key' => 'field_5209b27f33dd7',
            'label' => 'Content',
            'name' => 'content_6',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
        ),
        array (
          'key' => 'field_5209b27f33dd8',
          'label' => 'Background',
          'name' => 'background_type_6',
          'type' => 'radio',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array (
            'none' => 'None',
            'color' => 'Solid color',
            'image' => 'Image',
          ),
          'other_choice' => 0,
          'save_other_choice' => 0,
          'default_value' => 'none',
          'layout' => 'vertical',
        ),
        array (
          'key' => 'field_5209b27f33dd9',
          'label' => 'Background image',
          'name' => 'image_6',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_5209b27f33dd8',
                        'operator' => '==',
                        'value' => 'image',
                    ),
                ),
            ),
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'acf_thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array (
            'key' => 'field_5209b27f33de0',
            'label' => 'Background Color',
            'name' => 'color_6',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_5209b27f33dd8',
                        'operator' => '==',
                        'value' => 'color',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'template-services.php',
            ),
        ),
    ),
    'menu_order' => 7,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array (
    'key' => 'group_52d0369b6c903',
    'title' => 'Columns Type 2',
    'fields' => array (
        array (
          'key' => 'field_52d0b27f33dd8',
          'label' => 'Background',
          'name' => 'background_type_cols_2',
          'type' => 'radio',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array (
            'none' => 'None',
            'color' => 'Solid color',
            'image' => 'Image',
          ),
          'other_choice' => 0,
          'save_other_choice' => 0,
          'default_value' => 'none',
          'layout' => 'vertical',
        ),
        array (
          'key' => 'field_52d0b27f33dd9',
          'label' => 'Background image',
          'name' => 'image_cols_2',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_52d0b27f33dd8',
                        'operator' => '==',
                        'value' => 'image',
                    ),
                ),
            ),
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'acf_thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array (
            'key' => 'field_52d0b27f33de0',
            'label' => 'Background Color',
            'name' => 'color_cols_2',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_52d0b27f33dd8',
                        'operator' => '==',
                        'value' => 'color',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),
        array (
            'key' => 'field_52d037e303106',
            'label' => 'Columns',
            'name' => 'columns_2_columns_2',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => '',
            'max' => '',
            'layout' => 'block',
            'button_label' => 'Add Column',
            'sub_fields' => array (
                array (
                    'key' => 'field_52d037e903107',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array (
                    'key' => 'field_52d037f303108',
                    'label' => 'Title',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array (
                    'key' => 'field_52d037f703109',
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                ),
                array (
                    'key' => 'field_52d037a303111',
                    'label' => 'Link title',
                    'name' => 'link_title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array (
                    'key' => 'field_52d037f303110',
                    'label' => 'Link url',
                    'name' => 'link_url',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
            ),
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'template-services.php',
            ),
        ),
    ),
    'menu_order' => 8,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => ['the_content'],
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array (
    'key' => 'group_5210b274c7d49',
    'title' => 'Services Content Block 7',
    'fields' => array (
        array (
            'key' => 'field_5210b27f33dd7',
            'label' => 'Content',
            'name' => 'content_7',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
        ),
        array (
          'key' => 'field_5210b27f33dd8',
          'label' => 'Background',
          'name' => 'background_type_7',
          'type' => 'radio',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array (
            'none' => 'None',
            'color' => 'Solid color',
            'image' => 'Image',
          ),
          'other_choice' => 0,
          'save_other_choice' => 0,
          'default_value' => 'none',
          'layout' => 'vertical',
        ),
        array (
          'key' => 'field_5210b27f33dd9',
          'label' => 'Background image',
          'name' => 'image_7',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_5210b27f33dd8',
                        'operator' => '==',
                        'value' => 'image',
                    ),
                ),
            ),
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'acf_thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array (
            'key' => 'field_5210b27f33de0',
            'label' => 'Background Color',
            'name' => 'color_7',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_5210b27f33dd8',
                        'operator' => '==',
                        'value' => 'color',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'template-services.php',
            ),
        ),
    ),
    'menu_order' => 9,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array (
    'key' => 'group_5211b274c7d49',
    'title' => 'Services Content Block 8',
    'fields' => array (
        array (
            'key' => 'field_5211b27f33dd7',
            'label' => 'Content',
            'name' => 'content_8',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
        ),
        array (
          'key' => 'field_5211b27f33dd8',
          'label' => 'Background',
          'name' => 'background_type_8',
          'type' => 'radio',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array (
            'none' => 'None',
            'color' => 'Solid color',
            'image' => 'Image',
          ),
          'other_choice' => 0,
          'save_other_choice' => 0,
          'default_value' => 'none',
          'layout' => 'vertical',
        ),
        array (
          'key' => 'field_5211b27f33dd9',
          'label' => 'Background image',
          'name' => 'image_8',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_5211b27f33dd8',
                        'operator' => '==',
                        'value' => 'image',
                    ),
                ),
            ),
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'acf_thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array (
            'key' => 'field_5211b27f33de0',
            'label' => 'Background Color',
            'name' => 'color_8',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_5211b27f33dd8',
                        'operator' => '==',
                        'value' => 'color',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'template-services.php',
            ),
        ),
    ),
    'menu_order' => 10,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => [0 => 'the_content'],
    'active' => 1,
    'description' => '',
));

endif;