<?php return array(
  array (
    'key' => 'field__header_minihero_subtitle__luca_foto',
    'label' => 'Header subtitle',
    'name' => 'header_minihero_subtitle',
    'type' => 'text',
    'instructions' => 'Subtitle displayed below the title in header',
    'default_value' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array (
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'allow_null' => 1,
    'allow_multiple' => 0,
  ),
  array (
    'key' => 'field__header_minihero_link_label__luca_foto',
    'label' => 'Header link label',
    'name' => 'header_minihero_link_label',
    'type' => 'text',
    'instructions' => '',
    'default_value' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array (
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'allow_null' => 1,
    'allow_multiple' => 0,
  ),
  array (
    'key' => 'field__header_minihero_link_url__luca_foto',
    'label' => 'Header link url',
    'name' => 'header_minihero_link_url',
    'type' => 'text',
    'instructions' => '',
    'default_value' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array (
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'allow_null' => 1,
    'allow_multiple' => 0,
  ),
);
