<?php return array (
            'key' => 'field_59d1380c0310a',
            'label' => 'Background image',
            'name' => 'testimonials_background_image',
            'type' => 'image',
            'instructions' => '',
            'required' => '',
            'conditional_logic' => '',
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        );