<?php
if ( function_exists( 'acf_add_local_field_group' ) ):

	acf_add_local_field_group( array(
		'key' => 'group_6498eca8249ae',
		'title' => 'TV',
		'fields' => array(
			array(
				'key' => 'field_6498eca9a558f',
				'label' => 'Block Title',
				'name' => 'block_title',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'admin_only' => 0,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_6498ecb9f5690',
				'label' => 'Featured Video',
				'name' => 'featured_video',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'admin_only' => 0,
				'post_type' => array(
					0 => 'video',
				),
				'post_status' => array(
					0 => 'publish',
				),
				'taxonomy' => '',
				'return_format' => 'object',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 1,
			),
			array(
				'key' => 'field_6498ff7b9a3b7',
				'label' => 'Featured Video Content',
				'name' => 'featured_video_content',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'admin_only' => 0,
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_6498f1240a83d',
				'label' => 'Videos',
				'name' => 'videos',
				'aria-label' => '',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'admin_only' => 0,
				'post_type' => array(
					0 => 'video',
				),
				'post_status' => array(
					0 => 'publish',
				),
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
				),
				'return_format' => 'object',
				'min' => 1,
				'max' => '',
				'elements' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-front.php',
				),
			),
			array(
				array(
					'param' => 'post_template',
					'operator' => '==',
					'value' => 'template-tv.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'the_content',
			1 => 'excerpt',
		),
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

	acf_add_local_field_group( array(
		'key' => 'group_6498f3e925a4d',
		'title' => 'TV Video',
		'fields' => array(
			array(
				'key' => 'field_6498b3e976983',
				'label' => 'Video',
				'name' => 'video',
				'aria-label' => '',
				'type' => 'oembed',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'admin_only' => 0,
				'width' => 750,
				'height' => 480,
			),
			array(
				'key' => 'field_6598b4175972c',
				'label' => 'Thumbnail',
				'name' => 'thumbnail',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'admin_only' => 0,
				'return_format' => 'array',
				'library' => 'all',
				'min_width' => '200',
				'min_height' => '100',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'preview_size' => 'medium',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'video',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'the_content',
			1 => 'excerpt',
		),
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

endif;
